### ISSUE TITLE
Move content from GDocs to Docusaurus

### ISSUE THREAD

**Issue by AlexLakatos** [interledger/webmonetization.dev#3]
Create new issues and separate pages for all files in this GDrive folder: https://drive.google.com/drive/folders/1LtnUwENXGgioFQ10T0Qg0320_ypewdS8?usp=sharing

**Comment by mankins** [comment]
@AlexLakatos  To clarify this, are you asking to create new GitHub issues for each page in the GDrive folder? or to actually implement those documents as markdown, etc?

**Comment by AlexLakatos** [comment]
Both.

**Comment by mkurapov** [comment]
Is this still relevant? @AlexLakatos

**Comment by huijing** [comment]
No longer relevant.
